/*
 * generated by Xtext
 */
package DAGx.ui.contentassist

import DAGx.ui.contentassist.AbstractDAGxProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class DAGxProposalProvider extends AbstractDAGxProposalProvider {
}
