/*
 * generated by Xtext
 */
package DAGx.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DAGxUiModule extends DAGx.ui.AbstractDAGxUiModule {
	public DAGxUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
